Необходимо реализовать следующую задачу: написать утилиту переноса книг из Apple
iBooks.app на уделанный сервер с помощью ssh/scp

Утилита консольная.

Алгоритм переноса в общем виде:
- получение списка книг из локальной базы данных iBooks, расположенной по пути
  "/Users/anton/Library/Containers/com.apple.iBooksX/Data/Documents/BKLibrary/BKLibrary-1-091020131601.sqlite"
  функция для получения списка книг уже написана в файле [[file:src/ibooks_migration/db/ibooks.clj]] - get-books
- преобразование сущности БД во внутреннюю сущность утилиты с помощью функции
  ibooks-record->task [[file:src/ibooks_migration/task.clj]]
- проверка что данная книга еще не была мигрирована - task-done?  функция в файле [[file:src/ibooks_migration/db/migrator.clj]]
- валидация полученного пути - он должен существовать, в файле [[file:src/ibooks_migration/book.clj]] уже реализованы
  функции:
  - book-exists?
  - valid-ibooks?
  - valid-pdf?
  - valid-epub?
- ограничение количества места, занятого скачанными книгами. Максимальный размер скачанных в моменте книг не
  должен превышать значения, задаваемого конфигов. Кажется целесообразным хранить текущее выделенное значение
  в атоме, инкрементировать его когда задача пропускается далее и вычитать по хуку, который будет добавлен в
  сущность task и передан далее в обработку. Хук должен быть карирован (partial) размером книги в текущей таске,
  чтобы потом не пришлось его вычислять.
- подготовка книги:
  - pdf нужно просто скачать. поскольку файл скорее всего будет лежать в облаке, его необходимо предварительно
    скачать с помощью brctl download и дождаться момента когда он будет скачан. Функции для этого уже
    реализованы в файле [[file:src/ibooks_migration/icloud/core.clj]]:
    - dataless? - проверяет атрибут dataless, если он true - значит локально на диске лежит только заглушка,
      файл фактически не скачан
    - brctl-download
    - brctl-evict
  - epub обычно лежит в распакованном виде, поэтому надо сперва скачать директорию и все вложенные файлы.
    После этого необходимо заново собрать исходный epub-архив во временной директории, не включая файлы,
    которые могли быть добавлены самим iBooks.app после распаковки. На дальнейшие шаги должен передаваться
    именно этот временный архив, а не директория из managed storage
    - при пересборке нельзя полагаться на то, что содержимое всегда лежит в OEBPS. Встречаются как минимум
      варианты с OEBPS, OPS и файлами публикации в корне контейнера. Источник истины для пересборки:
      META-INF/container.xml -> package document (.opf) -> manifest
    - в архив обязательно должны входить container files, необходимые для epub-контейнера
      (mimetype, META-INF/container.xml и другие релевантные файлы контейнера), а также publication resources
      из manifest package document
    - из локальной директории iBooks не нужно переносить iTunesMetadata.plist и iTunesMetadata-original.plist:
      это локальные метаданные Apple/iTunes, а не часть публикации
    - если присутствует META-INF/com.apple.ibooks.display-options.xml, его следует сохранять: это Apple Display
      Options file, то есть Apple-специфичные layout metadata для EPUB 2, а не локальный мусор библиотеки
  - ibooks игнорируем - их обрабатывать не нужно

  В конце этого этапа у нас должен быть файл, с которым мы можем проводить дальнейшие манипуляции.
  Кроме того на этом же этапе необходимо вычислить md5sum, функция для этого уже написана (md5sum) в файле
  [[file:src/ibooks_migration/book.clj]]
- файл необходимо залить на удаленную машину с помощью scp. Корень удаленной директории берется из конфига.
  Файл копируется как есть с перезаписью, дополнительных проверок на то, что он уже существует на удаленной
  стороне, не требуется: признак успешной миграции хранится в локальной базе утилиты
- после заливки необходимо посчитать md5sum на удаленной машине с помощью ssh-md5sum
  (смотри [[file:src/ibooks_migration/book.clj]]) и сравнить локальную и удаленную суммы
- после успешной проверки необходимо выполнить очистку:
  - для файла из iCloud managed storage вызвать brctl-evict и с помощью dataless? дождаться, что он действительно
    уже вытеснен с диска
  - если для epub был собран временный архив, удалить его отдельно, например через rm -f /tmp/%{BOOK}.epub
- как финальный шаг добавить запись в локальную базу о том что данная книга уже обработана - task-done!
  в файле [[file:src/ibooks_migration/db/migrator.clj]]

Разрешенные библиотеки (зависимости):
все разрешенные для использования библиотеки уже добавлены в deps.edn. если целесообразно решить задачу с использованием
какой то дополнительной библиотеки - спроси об этом явно

Стиль кода:
- функциональный подход в целом - функция должна выполнять только одну задачу
- если функция решает задачу только какого то одного блока кода, вызывается из одного места, то стоит ее обьявить в let
  блоке той функции которая ее использует
- читаемость и наглядность важна больше чем функциональная разбивка
- заимствовать лучшие стороны литературного програмирования - очевидные куски кода не нужно документировать, семантически
  плотные - нужно, но без фанатизма, комментарии должны быть короткими и четкими

Ограничения и архитектура приложения:
- общий объем мигрируемых книг - порядка 800 Гбайт. это накладывает требования на архитектуру - должна быть использована
  многопоточность
- многопоточность может быть обеспечена использованием каналов и go/go-loop
- в данном случае пайплайн - линейный, в общем же случае это граф
- воркер взаимодействует с супервизором через каналы. стандартный набор каналов - input-ch, output-ch, command-ch, event-ch
- воркеры (все указанные воркеры связаны последовательно):
  - :worker/get-books: (scale 1)
    запрашивает список книг из базы ibooks с помощью одноименной функции, уже реализованной. функция возвращает вектор
    хэш мап в котором десятки тысяч сущностей. элементы этой последовательности необходимо отправлять в output=ch по одному,
    при этом продолжать слушать command-ch. как вариант после получения результата этой функции можно создать буферизованный
    канал размера равного размеру последовательности и с помощью alt (core.async) слушать события из command-ch и этого канала,
    отдавая приоритет command-ch
  - :worker/task-preparation: (scale 1)
    задача данного воркера:
    - получать из input-ch от :worker/get-books строки из базы данных по одной
    - преобразовывать их в мапу task функцией ibooks-record->task
    - проверять не была ли еще выполнена такая задача функцией task-done? если уже была - отбрасывать ее
    - проверять, валидный ли путь (ключ :path) - book-exists? если нет - отбрасывать задачу и логировать о том что таска уже
      была выполнена
    - если файл epub (-> :path file-name file-extension) то добавить ключ :src-path "/tmp/(-> :path file-name)", иначе :src-path path
      установить также поле :format #{epub, pdf} в зависимости от экстеншена
  - :worker/task-throttler: (scale 1)
    При запуске получает аргумент max-disk-space-usage в байтах. Создает локальный стейт current-disk-space-usage, инициализируя 0.
    Получает таску из input-ch, определяет размер path с помощью fs-size. Если fs-size + current-disk-space-usage <= max-disk-space-usage
    то обновляет current-disk-space-usage, добавляет к таске ключ :throttler-callback, значение - лямбда функция которая уменьшит
    current-disk-space-usage на fs-size - то есть таким образом будет отмечено что место освободилось.
    Если же fs-size + current-disk-space-usage > max-disk-space-usage - запускает цикл ожидания по 100мс и после каждого ожидания
    обязательно проверяет command-ch и условие. Локальный стейт current-disk-space-usage должен быть атомом в связи с конкурентным
    доступом к нему
  - :worker/downloader: (scale: 8)
    получает задачу из input-ch, вызывает brctl-download по (task :path), с помощью dataless? ожидает, когда загрузка будет завершена -
    dataless? должен быть false. Проверки dataless? - циклично, раз в 100мс. Между проверками необходимо продолжать проверять command-ch -
    крупный файл не основание откладывать останов всего сервиса
  - :worker/epub-packer: (scale: 2)
    получает таску из input-ch, если файл - epub (-> task :format)  запускает pack-epub! :path :src-path и передает задачу в output-ch
    если файл не epub - передает задачу в output-ch ничего с ней не делая
    вызов pack-epub! не должен блокировать воркер, воркер должен продолжать слушать command-ch раз в 100 мс - это требование ко всем воркерам
  - :worker/uploader: (scale: 8)
    при инициализации получает как аргумент функцию (send-book [path]).
    считает с помощью md5sum (уже реализована) хеш :src-path и пишет его в :src-md5sum
    функция с помощью clojure.java.shell/sh вызывая scp отправляет path на удаленный хост, команда как пример
    scp :src-path razer:/mnt/books/(-> task :src-path file-name)
    считает хеш файла на удаленном хосте - ssh-md5sum (уже реализована)
    проверяет хеши - локальный и удаленный. если не равно - ошибка -> events-ch
  - :worker/cleaner: (scale: 8)
    :path - brctl evict и раз в 100мс ожидание dataless? = true
    :format = epub? если да - rm :src-path
  - :worker/finalizer
    получает коннект к локальной базе. миграция лежит в resources/migrations. ставит флаг done с помощью task-done!
- все воркеры, когда им нечего делать - nil из input-ch к примеру - отправляют в events-ch :done
- все воркеры не блокируются своими тяжелыми операциями и раз в 100мс проверяют command-ch на команду :stop
- все воркеры ловят исключения и если оно поймано - обработка завершается, отправляется сообщение :error в events-ch с вложенным
  объектом исключения и воркер завершает работу
- команды от супервизора - только :stop, воркер отвечает :stopped и завершает работу
- пайплайн должен строиться декларативно. пример:
  #+begin_src clojure
    (def pipeline
      {:worker/get-books {:db ibooks-db-connection}
       :worker/task-preparation {:input (self/ref :worker/get-books)
                                 :db migrator-db-connection}
       :worker/task-throttler {:input (self/ref :worker/task-preparation)
                               :max-disk-space-usage (math/pow 2 33) ;; 8 Гбайт
                               }
       :worker/downloader {:input (self/ref :worker/task-throttler) :scale 8}
       :worker/epub-packer {:input (self/ref :worker/downloader) :scale 2}
       :worker/uploader {:input (self/ref :worker/epub-packer :send-book-fn ssh-send-fn) :scale 8}
       :worker/cleaner {:input (self/ref :worker/cleaner)
                        :scale 8}
       :worker/finalizer {:input (self/ref :worker/cleaner)
                          :db migrator-db-connection}})
  #+end_src
- во время запуска (создания) пайплайна из конфига алгоритм проходит по ключам конфига и смотрит на зависимости self/ref и если
  для него нет инстанса в этом конфиге - проваливается рекурсивно в него и повторяет цикл. пока не найдет ту зависимость которая
  не имеет иных внешних - инстансирует воркер, добавляет его в конфиг по ключу названия воркера и ключу :self.
  имеет смысл при таком проходе заполнить ключи :output - они нужны будут при остановке графа

* TASKS
База ibooks - "/Users/anton/Library/Containers/com.apple.iBooksX/Data/Documents/BKLibrary/BKLibrary-1-091020131601.sqlite"
- [X] Выяснение особенностей хранения epub
  - есть основание полагать что все пути в базе - директории (в выборке из 10 все были директориями)
  - файлы:
    - iTunesMetadata.plist
    - iTunesMetadata-original.plist
    являются Apple-specific и копировать их не нужно
  - валидация можно осуществлять с помощью epubcheck - официального валидатора предоставляемого w3c
  - проверь особенности работы команды brctl download - при вызове команды к ZPATH происходит скачивание всей директории
    включая файлы внутри или нет. Узнать это ты можешь с помощью команды stat -f '%Sf' ${ZPATH} - если есть атрибут
    dataless значит файл не скачан
  - первый драфт алгоритма пересборки такой:
    - создать zip-архив
    - записать mimetype первым и без сжатия
    - добавить все остальные файлы как есть
    - исключить iTunesMetadata.plist
    - исключить iTunesMetadata-original.plist
    - затем прогнать epubcheck ${ARCH_PATH}
- [X] brctl
  - download качает всю директорию, снятие dataless означает что вся директория готова к использованию
  - evict спустя какое то время приводит к вытеснению всех файлов внутри директории
- [X] Напиши код в src/ibooks_migration/epub.clj, который реализует сжатие epub директории в epub zip архив:
  - создать zip-архив
  - записать mimetype первым и без сжатия
  - добавить все остальные файлы как есть
  - исключить iTunesMetadata.plist
  - исключить iTunesMetadata-original.plist
  - результат: реализована функция pack-epub! в [[file:src/ibooks_migration/epub.clj]]
- [X] Настройка размера воркер пула clojure.core.async во время запуска
  Используй clojure.core.async.executor-factory для настройки размера пула - пул должен быть равен удвоенному количеству
  ядер на текущей машине (то есть опрелели это значение в рантайме). Реализуй это в файле src/ibooks_migration/core.clj
- [X] Определение размера книги по ZPATH
  iCloud выставляет корректный размер для файлов-заглушек (когда файл не скачан).
  Реализуй функцию определения размера файла/файлов лежащих по path (аргумент) - (defn fs-size [path])
  если path - директория - вызови + рекурсивно по списку файлов внутри, если файл - верни размер в байтах.
  Стандартная рекурсивная функция.
- [X] Доработка конфигурации
  Я прописал пример конфига в run/config.edn
  Я создал src/ibooks_migration/config.clj - весь код связанный с парсингом и валидацией конфига пиши в него
  - [X] проверь его формат, все ли аргументы в нем указаны? если нет - останови свою работу и запроси изменение
  - [X] замени парсинг аргументов командной строки на clojure.tools.cli. нужен только один аргумент - --config -
    путь до конфига. он обязательный и дефолтного значения не имеет
  - [X] напиши валидатор конфига. все параметры обязательные и имеют тип приведенный в run/config.edn в качестве
    примера. добавь текстовые сообщения к каждому полю - чтобы давать обратную связь на случай если конфиг некорректный
    парсер max-disk-space-usage уже написан в src/ibooks_migration/config.clj
  - [X] убери из runtime-config все дефолты, все параметры только из конфига и обязательные

* Черновик (не учитывать в работе):
** clj-condo:
- Линтить Clojure, ClojureScript и .cljc код на типовые ошибки и smell’ы.
- Находить синтаксические и семантические проблемы до запуска программы.
- Проверять ns-формы: неиспользуемые require, refer, import, алиасы, конфликты имен.
- Ловить неиспользуемые локальные bindings, аргументы, private vars.
- Подсвечивать подозрительные конструкции: неверная арность, недостижимые ветки в ряде случаев, shadowing, misplaced docstrings и т.п.
- Понимать многие стандартные макросы и позволять обучать линтер собственным макросам через конфиг.
- Работать как быстрый standalone линтер в CLI, в CI и в редакторах.
- Давать основу для IDE-функций через clojure-lsp: diagnostics, navigation, references, rename и др.
- Экспортировать analysis data, которую можно использовать для более глубоких инструментов и запросов по кодовой базе.
- Конфигурироваться очень тонко: включение/выключение линтеров, уровни severity, hooks, macro-expansion hints.
- Поддерживать linters для стиля, correctness и maintainability, а не только compile-time ошибок.
- Частично помогать искать неиспользуемый код, но не быть полноценным whole-program dead code analyzer.

** Рантайм
я то думал над другой схемой
сложно объяснить словами но давай попробую

граф описывается документом - как сейчас, мапой
ребра графа - каналы. один и тот же канал для кого то output-ch, а для следующего - input-ch
есть еще command-ch и event-ch - эти каналы нужны супервизору чтобы получать ошибки от узлов и останавливать весь граф. для остановки графа 2 причины - ошибка в каком то узле
(любом сейчас) - тогда останов принудительный - отправка всем :stop (кроме того кто сигнализировал об ошибке) и получение от всех :stopped

каналы синхронные. это не является проблемой.
если get-books завершил свою работу он отправляет :stopped -> events-ch
супервизор получив от него :stopped закрывает его канал и ждет следующего :stopped и так далее пока не получит от всех это сообщение

тут говорим о 4 ключевых сущностях
1. описание пайплайна - мапа с ключами (default-pipeline был в коде) - ВАЖНО! она же является стейтом когда на основе нее начинают собирать пайплайн живой. в нее добавляют
рантайм информацию. в ней может хранится информация о состоянии каждого воркера. аля кубернетис подход
2. хендлер - функция которая выполняется. получила значение, обработала и вернула другое значение или выкинула исключение
3. враппер хендлера - связь между супервизором и хендлером. крутит цикл, реагирует на command-ch, ловит исключения от хендлера и кидает ошибку в events-ch. получает данные из
input-ch и вызывает хендлер, его резульат кидает в output-ch
4. супервизор - по сути один метод (start!) - получает документ "описание пайплайна", запускает все зависимости и дописывает что нужно в "описание пайплайна" и вообщем то
обрабатывает два сценария (1) кто то выкинул ошибку - green shutdown всего (2) кто то завершился - green shutdown всего
