Необходимо реализовать следующую задачу: написать утилиту переноса книг из Apple
iBooks.app на уделанный сервер с помощью ssh/scp

Утилита консольная.

Алгоритм переноса в общем виде:
- получение списка книг из локальной базы данных iBooks, расположенной по пути
  "/Users/anton/Library/Containers/com.apple.iBooksX/Data/Documents/BKLibrary/BKLibrary-1-091020131601.sqlite"
  функция для получения списка книг уже написана в файле [[file:src/ibooks_migration/db/ibooks.clj]] - get-books
- преобразование сущности БД во внутреннюю сущность утилиты с помощью функции
  ibooks-record->task [[file:src/ibooks_migration/task.clj]]
- проверка что данная книга еще не была мигрирована - task-done?  функция в файле [[file:src/ibooks_migration/db/migrator.clj]]
- валидация полученного пути - он должен существовать, в файле [[file:src/ibooks_migration/book.clj]] уже реализованы
  функции:
  - book-exists?
  - valid-ibooks?
  - valid-pdf?
  - valid-epub?
- ограничение количества места, занятого скачанными книгами. Максимальный размер скачанных в моменте книг не
  должен превышать значения, задаваемого конфигов. Кажется целесообразным хранить текущее выделенное значение
  в атоме, инкрементировать его когда задача пропускается далее и вычитать по хуку, который будет добавлен в
  сущность task и передан далее в обработку. Хук должен быть карирован (partial) размером книги в текущей таске,
  чтобы потом не пришлось его вычислять.
- подготовка книги:
  - pdf нужно просто скачать. поскольку файл скорее всего будет лежать в облаке, его необходимо предварительно
    скачать с помощью brctl download и дождаться момента когда он будет скачан. Функции для этого уже
    реализованы в файле [[file:src/ibooks_migration/icloud/core.clj]]:
    - dataless? - проверяет атрибут dataless, если он true - значит локально на диске лежит только заглушка,
      файл фактически не скачан
    - brctl-download
    - brctl-evict
  - epub обычно лежит в распакованном виде, поэтому надо сперва скачать директорию и все вложенные файлы.
    После этого необходимо заново собрать исходный epub-архив во временной директории, не включая файлы,
    которые могли быть добавлены самим iBooks.app после распаковки. На дальнейшие шаги должен передаваться
    именно этот временный архив, а не директория из managed storage
    - при пересборке нельзя полагаться на то, что содержимое всегда лежит в OEBPS. Встречаются как минимум
      варианты с OEBPS, OPS и файлами публикации в корне контейнера. Источник истины для пересборки:
      META-INF/container.xml -> package document (.opf) -> manifest
    - в архив обязательно должны входить container files, необходимые для epub-контейнера
      (mimetype, META-INF/container.xml и другие релевантные файлы контейнера), а также publication resources
      из manifest package document
    - из локальной директории iBooks не нужно переносить iTunesMetadata.plist и iTunesMetadata-original.plist:
      это локальные метаданные Apple/iTunes, а не часть публикации
    - если присутствует META-INF/com.apple.ibooks.display-options.xml, его следует сохранять: это Apple Display
      Options file, то есть Apple-специфичные layout metadata для EPUB 2, а не локальный мусор библиотеки
  - ibooks игнорируем - их обрабатывать не нужно

  В конце этого этапа у нас должен быть файл, с которым мы можем проводить дальнейшие манипуляции.
  Кроме того на этом же этапе необходимо вычислить md5sum, функция для этого уже написана (md5sum) в файле
  [[file:src/ibooks_migration/book.clj]]
- файл необходимо залить на удаленную машину с помощью scp. Корень удаленной директории берется из конфига.
  Файл копируется как есть с перезаписью, дополнительных проверок на то, что он уже существует на удаленной
  стороне, не требуется: признак успешной миграции хранится в локальной базе утилиты
- после заливки необходимо посчитать md5sum на удаленной машине с помощью ssh-md5sum
  (смотри [[file:src/ibooks_migration/book.clj]]) и сравнить локальную и удаленную суммы
- после успешной проверки необходимо выполнить очистку:
  - для файла из iCloud managed storage вызвать brctl-evict и с помощью dataless? дождаться, что он действительно
    уже вытеснен с диска
  - если для epub был собран временный архив, удалить его отдельно, например через rm -f /tmp/%{BOOK}.epub
- как финальный шаг добавить запись в локальную базу о том что данная книга уже обработана - task-done!
  в файле [[file:src/ibooks_migration/db/migrator.clj]]

Разрешенные библиотеки (зависимости):
все разрешенные для использования библиотеки уже добавлены в deps.edn. если целесообразно решить задачу с использованием
какой то дополнительной библиотеки - спроси об этом явно

Стиль кода:
- функциональный подход в целом - функция должна выполнять только одну задачу
- если функция решает задачу только какого то одного блока кода, вызывается из одного места, то стоит ее обьявить в let
  блоке той функции которая ее использует
- читаемость и наглядность важна больше чем функциональная разбивка
- заимствовать лучшие стороны литературного програмирования - очевидные куски кода не нужно документировать, семантически
  плотные - нужно, но без фанатизма, комментарии должны быть короткими и четкими

Ограничения и архитектура приложения:
- общий объем мигрируемых книг - порядка 800 Гбайт. это накладывает требования на архитектуру - должна быть использована
  многопоточность
- многопоточность может быть обеспечена использованием каналов и go/go-loop
- в данном случае пайплайн - линейный, в общем же случае это граф
- воркер взаимодействует с супервизором через каналы. стандартный набор каналов - input-ch, output-ch, command-ch, event-ch
- воркеры (все указанные воркеры связаны последовательно):
  - :worker/get-books: (scale 1)
    запрашивает список книг из базы ibooks с помощью одноименной функции, уже реализованной. функция возвращает вектор
    хэш мап в котором десятки тысяч сущностей. элементы этой последовательности необходимо отправлять в output=ch по одному,
    при этом продолжать слушать command-ch. как вариант после получения результата этой функции можно создать буферизованный
    канал размера равного размеру последовательности и с помощью alt (core.async) слушать события из command-ch и этого канала,
    отдавая приоритет command-ch
  - :worker/task-preparation: (scale 1)
    задача данного воркера:
    - получать из input-ch от :worker/get-books строки из базы данных по одной
    - преобразовывать их в мапу task функцией ibooks-record->task
    - проверять не была ли еще выполнена такая задача функцией task-done? если уже была - отбрасывать ее
    - проверять, валидный ли путь (ключ :path) - book-exists? если нет - отбрасывать задачу и логировать о том что таска уже
      была выполнена
    - если файл epub (-> :path file-name file-extension) то добавить ключ :src-path "/tmp/(-> :path file-name)", иначе :src-path path
      установить также поле :format #{epub, pdf} в зависимости от экстеншена
  - :worker/task-throttler: (scale 1)
    При запуске получает аргумент max-disk-space-usage в байтах. Создает локальный стейт current-disk-space-usage, инициализируя 0.
    Получает таску из input-ch, определяет размер path с помощью fs-size. Если fs-size + current-disk-space-usage <= max-disk-space-usage
    то обновляет current-disk-space-usage, добавляет к таске ключ :throttler-callback, значение - лямбда функция которая уменьшит
    current-disk-space-usage на fs-size - то есть таким образом будет отмечено что место освободилось.
    Если же fs-size + current-disk-space-usage > max-disk-space-usage - запускает цикл ожидания по 100мс и после каждого ожидания
    обязательно проверяет command-ch и условие. Локальный стейт current-disk-space-usage должен быть атомом в связи с конкурентным
    доступом к нему
  - :worker/downloader: (scale: 8)
    получает задачу из input-ch, вызывает brctl-download по (task :path), с помощью dataless? ожидает, когда загрузка будет завершена -
    dataless? должен быть false. Проверки dataless? - циклично, раз в 100мс. Между проверками необходимо продолжать проверять command-ch -
    крупный файл не основание откладывать останов всего сервиса
  - :worker/epub-packer: (scale: 2)
    получает таску из input-ch, если файл - epub (-> task :format)  запускает pack-epub! :path :src-path и передает задачу в output-ch
    если файл не epub - передает задачу в output-ch ничего с ней не делая
    вызов pack-epub! не должен блокировать воркер, воркер должен продолжать слушать command-ch раз в 100 мс - это требование ко всем воркерам
  - :worker/uploader: (scale: 8)
    при инициализации получает как аргумент функцию (send-book [path]).
    считает с помощью md5sum (уже реализована) хеш :src-path и пишет его в :src-md5sum
    функция с помощью clojure.java.shell/sh вызывая scp отправляет path на удаленный хост, команда как пример
    scp :src-path razer:/mnt/books/(-> task :src-path file-name)
    считает хеш файла на удаленном хосте - ssh-md5sum (уже реализована)
    проверяет хеши - локальный и удаленный. если не равно - ошибка -> events-ch
  - :worker/cleaner: (scale: 8)
    :path - brctl evict и раз в 100мс ожидание dataless? = true
    :format = epub? если да - rm :src-path
  - :worker/finalizer
    получает коннект к локальной базе. миграция лежит в resources/migrations. ставит флаг done с помощью task-done!
- все воркеры, когда им нечего делать - nil из input-ch к примеру - отправляют в events-ch :done
- все воркеры не блокируются своими тяжелыми операциями и раз в 100мс проверяют command-ch на команду :stop
- все воркеры ловят исключения и если оно поймано - обработка завершается, отправляется сообщение :error в events-ch с вложенным
  объектом исключения и воркер завершает работу
- команды от супервизора - только :stop, воркер отвечает :stopped и завершает работу
- пайплайн должен строиться декларативно. пример:
  #+begin_src clojure
    (def pipeline
      {:worker/get-books {:db ibooks-db-connection}
       :worker/task-preparation {:input (self/ref :worker/get-books)
                                 :db migrator-db-connection}
       :worker/task-throttler {:input (self/ref :worker/task-preparation)
                               :max-disk-space-usage (math/pow 2 33) ;; 8 Гбайт
                               }
       :worker/downloader {:input (self/ref :worker/task-throttler) :scale 8}
       :worker/epub-packer {:input (self/ref :worker/downloader) :scale 2}
       :worker/uploader {:input (self/ref :worker/epub-packer :send-book-fn ssh-send-fn) :scale 8}
       :worker/cleaner {:input (self/ref :worker/cleaner)
                        :scale 8}
       :worker/finalizer {:input (self/ref :worker/cleaner)
                          :db migrator-db-connection}})
  #+end_src
- во время запуска (создания) пайплайна из конфига алгоритм проходит по ключам конфига и смотрит на зависимости self/ref и если
  для него нет инстанса в этом конфиге - проваливается рекурсивно в него и повторяет цикл. пока не найдет ту зависимость которая
  не имеет иных внешних - инстансирует воркер, добавляет его в конфиг по ключу названия воркера и ключу :self.
  имеет смысл при таком проходе заполнить ключи :output - они нужны будут при остановке графа

* TASKS
База ibooks - "/Users/anton/Library/Containers/com.apple.iBooksX/Data/Documents/BKLibrary/BKLibrary-1-091020131601.sqlite"
- [X] Выяснение особенностей хранения epub
  - есть основание полагать что все пути в базе - директории (в выборке из 10 все были директориями)
  - файлы:
    - iTunesMetadata.plist
    - iTunesMetadata-original.plist
    являются Apple-specific и копировать их не нужно
  - валидация можно осуществлять с помощью epubcheck - официального валидатора предоставляемого w3c
  - проверь особенности работы команды brctl download - при вызове команды к ZPATH происходит скачивание всей директории
    включая файлы внутри или нет. Узнать это ты можешь с помощью команды stat -f '%Sf' ${ZPATH} - если есть атрибут
    dataless значит файл не скачан
  - первый драфт алгоритма пересборки такой:
    - создать zip-архив
    - записать mimetype первым и без сжатия
    - добавить все остальные файлы как есть
    - исключить iTunesMetadata.plist
    - исключить iTunesMetadata-original.plist
    - затем прогнать epubcheck ${ARCH_PATH}
- [X] brctl
  - download качает всю директорию, снятие dataless означает что вся директория готова к использованию
  - evict спустя какое то время приводит к вытеснению всех файлов внутри директории
- [X] Напиши код в src/ibooks_migration/epub.clj, который реализует сжатие epub директории в epub zip архив:
  - создать zip-архив
  - записать mimetype первым и без сжатия
  - добавить все остальные файлы как есть
  - исключить iTunesMetadata.plist
  - исключить iTunesMetadata-original.plist
  - результат: реализована функция pack-epub! в [[file:src/ibooks_migration/epub.clj]]
- [X] Настройка размера воркер пула clojure.core.async во время запуска
  Используй clojure.core.async.executor-factory для настройки размера пула - пул должен быть равен удвоенному количеству
  ядер на текущей машине (то есть опрелели это значение в рантайме). Реализуй это в файле src/ibooks_migration/core.clj
- [X] Определение размера книги по ZPATH
  iCloud выставляет корректный размер для файлов-заглушек (когда файл не скачан).
  Реализуй функцию определения размера файла/файлов лежащих по path (аргумент) - (defn fs-size [path])
  если path - директория - вызови + рекурсивно по списку файлов внутри, если файл - верни размер в байтах.
  Стандартная рекурсивная функция.
- [-] Доработка конфигурации
  Я прописал пример конфига в run/config.edn
  Я создал src/ibooks_migration/config.clj - весь код связанный с парсингом и валидацией конфига пиши в него
  - [X] проверь его формат, все ли аргументы в нем указаны? если нет - останови свою работу и запроси изменение
  - [X] замени парсинг аргументов командной строки на clojure.tools.cli. нужен только один аргумент - --config -
    путь до конфига. он обязательный и дефолтного значения не имеет
  - [X] напиши валидатор конфига. все параметры обязательные и имеют тип приведенный в run/config.edn в качестве
    примера. добавь текстовые сообщения к каждому полю - чтобы давать обратную связь на случай если конфиг некорректный
    парсер max-disk-space-usage уже написан в src/ibooks_migration/config.clj
  - [X] убери из runtime-config все дефолты, все параметры только из конфига и обязательные
  - [ ] подключить hicari-cp и сделать сервисы для доступа к бд? транзакции то не нужны в целом. да пусть будут, быстрее
    написать чем обдумывать. можно конечно сделать просто макрос который будет оборачивать код в транзакцию
    так, сча проверю можно ли датасорс использовать как коннектабл в next.jdbc запросах
- [ ] реализовать враппер для получения строк из бд и отправки в out-ch
  логика какая?
  1. работаем в go-loop [cursor {}]
  2. cmd-ch inputs #{:stop} слушать с периодичностью 100мс - можно задать параметром
     если получили :stop - отвечаем в evt-ch :stopped и выходим
  3. выполняем запрос в базу в async/io-thread, получаем канал в котором будет либо исключение либо значение
     запрос в целом работает быстро, однако канал можно кинуть рекуром наверх.
  4. получать исключение жопа - надо все оборачивать. жопа говно. если получили исключение - надо сформировать из него
     событие и отправить в evt-ch и выйти
  5. если получили значение - надо пытаться утолкать его в out-ch не блокируясь
- [X] get-books worker
  - :row-retrieving - async/io-thread
  - :row-forwardingo
  - :stopping
  - :stopped
  - :failed
- [ ] обработка ошибок
  пока что в обработке ошибок бардак. в чем суть бардака - у нас два вида ошибок может быть:
  - ошибки при обработке конкретной таски - папка/файл отсутствует, упала заливка файла и мало ли что еще
    ошибки в целом на таких объемах данных надо куда то логировать, чтобы потом к ним вернуться. этим
    должен заниматься отдельный воркер
  - ошибки воркера - какие то нарушения в логике. состояние из которого нельзя перейти дальше. в таком случае воркер
    имеет право упасть но обязан рапортовать об этом.

  при неразрешимых проблемах воркер переходит в failed состояние. должно быть сформировано сообщение об ошибке.
  и его куда то надо закинуть.
  сообщение - что в него надо закинуть?
  1. код ошибки - keyword. все коды должны быть определены в одном месте
  2. контекст - сюда могут попасть все данные. однако эти данные по нормальному должны дополняться по мере всплывания
     ошибки вверх по каналам до основного супервизора. значит надо включать локальный контекст

  воркер не закрывает никакие полученные извне каналы самостоятельно. принцип такой - кто создал тот и освобождает.
  воркер не полагается на предположения о среде исполнения. воркер не делает предположений к примеру о том что
  канал
- [X] воркер троттлер
  
  описание FSM:
  #+begin_src clojure
    (def states
      [:task-waiting
       :size-calculation
       :disk-space-reservation
       :disk-space-release-waiting
       :task-forwarding
       :task-error-forwarding
       :stopping
       :stopped
       :failed])
  #+end_src
  - :task-awaiting
    channels: [cmd-ch, in-ch]
    transitions: [:stopping :size-calculation]

    cmd-ch -> nil (closed):
      in this implementation is not reasonable to handle this
      this case should never happen

    cmd-ch -> *command*:
      now only one is possible - :stop and action is to transit into :stopping

    in-ch -> nil (closed):
      transit to :stopping (reason - nothing to do)

    in-ch -> task:
      can it fail? no, it only reads channel and makes a transition

  - :size-calculation
    async/go fs-size and then
    channels: [cmd-ch, fs-size-ch]
    transitions: [:disk-space-reservation :task-error-forwarding :stopping]

    fs-size-ch -> exception
      one of possible actions is to signalize about it
      dont think exception is a enough reason to stop worker
      better lets forward it to error-ch
      -> :task-error-forwarding

    fs-size-ch -> size
      put it into task under :size key, if epub - x2
      and transit to :size

    cmd-ch = same behaviour

  - :disk-space-reservation
    non blocking behaviour
    channels: []
    transitions: [:task-forwarding :disk-space-release-waiting]

    if task-size > max-disk-space-usage -> :task-error-forwarding
    if enough                           -> :task-forwarding
    if not                              -> :disk-space-release-waiting

  - :disk-space-release-waiting
    channels: [cmd-ch disk-space-release-ch]
    transitions: [:disk-space-reservation :stopping]

    disk-space-release-ch -> number
    decrease current disk space usage and go to :disk-space-reservation

  - :task-forwarding
    sent task to out-ch and wait for message from task-forward-done-ch
    channels: [cmd-ch task-forward-done-ch]
    transitions: [:stopping :task-waiting]

  - :task-error-forwarding
    sends task processing exception to error-ch

  - :stopping
    do everything you need to clean and transit to :stopped

  - :stopped
    sent stopped event to evt-ch

  - :failed
    sent failed event to evt-ch

  states:
  - :waiting-task - cmd-ch in-ch
    тут все понятно, выполняется оба условия - команда не игнорируется, получаем таску

  - :calculating-size - cmd-ch result-ch
    запускаем тред, который вызовет диск и посчитает место
    если epub -> x2
    тред возвращает канал - мы его добавим в стейт и его же будем слушать (fs-size-ch)

  - :calculating-size-done - cmd-ch fs-size-ch
    пробуем резервировать - если места хватает - меняем стейт и переходим в :forwarding-task
    если не хватает - переходим в :not-enough-space

  - :reserving-space - без каналов, никаких блокировок
    если хватает - резервируем и на :forwarding-task
    в ином случае - :not-enough-space

  - :not-enough-space - cmd-ch space-freed-up-ch
    тут все просто - получаем space-freed-up-ch и переходим в :reserving-space

  - :forwarding-task - без каналов, просто отправка в горутине
    горутиной пинаем сообщение в out-ch и ждем подтверждение этого в forwarding-task-done-ch
    переходим в :waiting-task

  - :forwarding-task-done - cmd-ch, forwarding-task-done

  каким образом? каналы позволяют реализовать событийную модель, но это лишь один из подходов и он не всегда оправдан
  нет ничего плохого в блокировке гоурутины в принципе, однако она должна уметь завершаться если мы получаем
  команду остановки.
  ладно, доделаю как есть, а после уже буду анализировать. но сейчас пахнет откровенным переусложнением.
  а вообще - линукс к примеру блокирует процессы наглухо в ряде случаев и бывает даже ОС не может остановиться пока
  какие то сервисы не завершат корректно свою работу. в общем случае ты не знаешь что будет если ты остановишь сервис
  некорректно. к примеру, когда рассуждаешь об этом по отношению к базе данных никто тебе не гарантирует целостность
  данных кроме как база и ты обязан ждать пока она не вернет тебе управление

  что делаем с троттлером?
  есть несколько каналов:
  - команд
  - входной с задачами
  - входной с событиями "место освободилось"
  - выходной - "место занято"
  - атом или локальный стейт с занятым местом
  - настройка - предельное занятое место

  причина для итерации - команда или изменение стейта которое надо зафиксировать
  когда мы получаем задачу из канала - мы ее обратно туда уже не затолкаем. следовательно брать надо и
  до тех пор пока она не протолкнется - блокироваться. но не для обработки команд
  можно варьировать каналы в списке atls - если задача есть - убрать in-ch и ждать каналов которые урежут?

  последовательность действий:
  - получаем задачу
  - считаем размер, который нужно выделить. если это epub - резервируем x2
  - можем сейчас место выделить? - если да то вычитаем и отправляем задачу дальше
  - если нет - ждем освобождения места - только так.

  если рассматривать изолированно - для нас недопустимы блокировки
  первая причина блокировки - ожидание задачи из канала
  вторая - недостаток места и ожидание событий о освобождении
  третья - отправка таски дальше

  то есть мы имеем дело с автоматом в данном случае?
  то есть у нас изначальное состояние - :task-wait - по флоу мы ставим асинхронное ожидание таски и при получении
  отправляем в канал internal-events {:event :task-received :task task}
  на след итерации мы получаем из канала :task-received и наше действие - попробовать выделить место

  FSM!

  слушаем [cmd-ch result-ch result-send-ch] - блокируемся. но в таком случае мы не начнем работу
  значит надо что сделать? не блокироваться?
  если команда - ответ и выход
  если результат обработки получен - разбираемся что там и либо отвечаем ошибкой либо отправляем в out и ждем
  отправку через result-send-ch
  можно сделать канал задачи еще. ну пиздец, нагромождение какое то получается
- [X] prepare-tasks воркер
- [X] downloader
- [X] epub-packer
- [X] uploader
- [X] cleaner
- [X] finalizer

* В коде очень много дублирований, надо переделать. Процентов 80 кода - нарушение DRY

** Типичные шаги воркера

Доменные шаги
:checking-task-already-done
:checking-path-exists
:size-calculation
:disk-space-reservation
:disk-space-release-waiting
:starting-download
:waiting-download-completed
:packing-epub
:uploading-book
:calculating-local-md5
:calculating-remote-md5
:cleaning-epub
:starting-icloud-eviction
:checking-icloud-eviction-completed
:waiting-icloud-eviction-completed
:marking-task-done

Сервисные шаги, отношения к бизнес логике не имеют


:failed
:stopping
:stopped


:task-waiting
:receiving-task
:row-retrieving

:row-forwarding
:task-forwarding
:forwarding-task

:task-error-forwarding

Не все шаги про то чтобы:
- достать таску из канала
- запустить нужную функцию
- отдать результат в какой то канал

Есть и те которые требуют обработки в несколько шагов - это асинхронные шаги. Можно их держать в
отдельном треде - это правда. С другой стороны это нецелесообразное использование io-threads.
Есть также шаги которые зависят от нескольких каналов - как троттлер к примеру.
Можно начать с того что стандартизировать сервисные шаги - убрать дублирование кода.

Надо подумать... Пока непонятно как лучше сделать.

Очевидно что шаги бывают не из 1 функции, а с переходами. Значит FSM внутри воркеров нужна.
Вообщем то мысли убирать и не было. Воркер должен объявляться декларативнo.
То о чем я сейчас думаю это просто большая атомизация логики. Каждый воркер занимается в таком
случае только одной очень ограниченной областью деятельности.

Каждый шаг у меня характеризуется тем что ждет каких то данных из канала - завершения какой то операции
которая либо io-bound либо cpu-bound. И альтернативный канал который слушается - это cmd-ch

Блин, если я продолжу так перфекционистки выполнять это то ничего хорошего не будет, я просто буду
делать в разы меньше работы чем мог бы. С одной стороны есть процесс изучения - он характеризуется
тем что ты тратишь кучу времени, это нормально, это называется набивать шишки. Но я трачу это на задачу
которая отработает один раз и все, она больше мне нужна не будет. С другой стороны для вуки эта практика
полезна - там надо решать аналогичные проблемы.

что я сделаю:
- пайплайн это мапа - задается декларативно
- у пайплайна есть супервизор. он слушает сообщения (:stop только для остановки по сигналу) от главного
  потока и отвечает ему (дает результат работы)
- у каждой ноды пайплайна есть супервизор, который запускает нужный скейл воркеров и отвечает за их
  корректную остановку. супервизор пайплайна общается только с супервизором воркеров. по идее пайплайн
  можно в том числе динамически скейлить
- каждый воркер это FSM / go-loop. все исключения которые явно не обработаны - :failed переход. шаблонный код
  предоставляется автоматически - для обработки команд в том числе

Так. Давай хоть что то делать. Давай перетащим все обработчики в одно место. Сперва определим стейты - единым списком.
Через мультифункцию обрабатывать можно без проблем. Это уберет большую часть дублирования.

*** Получение задачи из канала
- слушаем cmd-ch / in-ch
- cmd-ch обрабатывает в данный момент только :stop команду. все что нужно - функцию которая получит
  state и произведет очистку перед остановкой.
- in-ch дает таску и нужно выполнить io bound or cpu bound job - тоже типичная штука. в общем случае это
  будет просто функцией, которая получит state, выполнит задачу и вернет новый стейт полагаю? мммм, по идее да,
  но

* Черновик (не учитывать в работе):
** clj-condo:
- Линтить Clojure, ClojureScript и .cljc код на типовые ошибки и smell’ы.
- Находить синтаксические и семантические проблемы до запуска программы.
- Проверять ns-формы: неиспользуемые require, refer, import, алиасы, конфликты имен.
- Ловить неиспользуемые локальные bindings, аргументы, private vars.
- Подсвечивать подозрительные конструкции: неверная арность, недостижимые ветки в ряде случаев, shadowing, misplaced docstrings и т.п.
- Понимать многие стандартные макросы и позволять обучать линтер собственным макросам через конфиг.
- Работать как быстрый standalone линтер в CLI, в CI и в редакторах.
- Давать основу для IDE-функций через clojure-lsp: diagnostics, navigation, references, rename и др.
- Экспортировать analysis data, которую можно использовать для более глубоких инструментов и запросов по кодовой базе.
- Конфигурироваться очень тонко: включение/выключение линтеров, уровни severity, hooks, macro-expansion hints.
- Поддерживать linters для стиля, correctness и maintainability, а не только compile-time ошибок.
- Частично помогать искать неиспользуемый код, но не быть полноценным whole-program dead code analyzer.

** Рантайм
я то думал над другой схемой
сложно объяснить словами но давай попробую

граф описывается документом - как сейчас, мапой
ребра графа - каналы. один и тот же канал для кого то output-ch, а для следующего - input-ch
есть еще command-ch и event-ch - эти каналы нужны супервизору чтобы получать ошибки от узлов и останавливать весь граф. для остановки графа 2 причины - ошибка в каком то узле
(любом сейчас) - тогда останов принудительный - отправка всем :stop (кроме того кто сигнализировал об ошибке) и получение от всех :stopped

каналы синхронные. это не является проблемой.
если get-books завершил свою работу он отправляет :stopped -> events-ch
супервизор получив от него :stopped закрывает его канал и ждет следующего :stopped и так далее пока не получит от всех это сообщение

тут говорим о 4 ключевых сущностях
1. описание пайплайна - мапа с ключами (default-pipeline был в коде) - ВАЖНО! она же является стейтом когда на основе нее начинают собирать пайплайн живой. в нее добавляют
рантайм информацию. в ней может хранится информация о состоянии каждого воркера. аля кубернетис подход
2. хендлер - функция которая выполняется. получила значение, обработала и вернула другое значение или выкинула исключение
3. враппер хендлера - связь между супервизором и хендлером. крутит цикл, реагирует на command-ch, ловит исключения от хендлера и кидает ошибку в events-ch. получает данные из
input-ch и вызывает хендлер, его резульат кидает в output-ch
4. супервизор - по сути один метод (start!) - получает документ "описание пайплайна", запускает все зависимости и дописывает что нужно в "описание пайплайна" и вообщем то
обрабатывает два сценария (1) кто то выкинул ошибку - green shutdown всего (2) кто то завершился - green shutdown всего

* Унификация

cleaner/receiving-task
- получаем сообщение из in-ch
- имея доступ к сообщению и стейту принимаем решение на какой стейт далее перейти

доступ к сообщению можно даже не иметь. ну то есть код может прописать :job ключ в стейте и
вызываемая функция может просто взять этот стейт и преобразовать как нужно. а транзит - это же просто изменение
ключа :state.

но receiving-task - это же типовая операция вообще то. что я хочу? не упоминать ее? типа как в фреймоврках делается?
это же плохая практика в кложе. в кложе все должно быть прозрачно.

типовая операция которая характеризуется каждый раз повторяемым кодом - если он повторяется, значит с этим надо что то
делать.

* Список воркеров и шаги которые они выполняют

** Список шагов
- получение строки из базы
- конвертация в таску
- обогащение таски
- проверка на то что таска уже была ранее выполнена
- проверка на то что файл на диске существует

- троттлинг таски исходя из используемого диска

- скачивание файлов
  завязано на даунстрим, не должно быть смешано с другой логикой. этот воркер должен только скачивать
  скейл 8

- упаковка epub
  один воркер более чем достаточен

- аплоад файлов на получатель
  упирается в сеть, не должен ничего кроме этого делать чтобы максимально ее загрузить
  скейл 8

- проверка хеш сумм
  1 воркер, более чем достаточно

- удаление epub
- освобождение файлов
- отметка таски как выполненной

** Обработка ошибок
