Необходимо реализовать следующую задачу: написать утилиту переноса книг из Apple
iBooks.app на уделанный сервер с помощью ssh/scp

Утилита консольная.

Алгоритм переноса в общем виде:
- получение списка книг из локальной базы данных iBooks, расположенной по пути
  "/Users/anton/Library/Containers/com.apple.iBooksX/Data/Documents/BKLibrary/BKLibrary-1-091020131601.sqlite"
  функция для получения списка книг уже написана в файле [[file:src/ibooks_migration/db/ibooks.clj]] - get-books
- преобразование сущности БД во внутреннюю сущность утилиты с помощью функции
  ibooks-record->task [[file:src/ibooks_migration/task.clj]]
- проверка что данная книга еще не была мигрирована - task-done?  функция в файле [[file:src/ibooks_migration/db/migrator.clj]]
- валидация полученного пути - он должен существовать, в файле [[file:src/ibooks_migration/book.clj]] уже реализованы
  функции:
  - book-exists?
  - valid-ibooks?
  - valid-pdf?
  - valid-epub?
- ограничение количества места, занятого скачанными книгами. Максимальный размер скачанных в моменте книг не
  должен превышать значения, задаваемого конфигов. Кажется целесообразным хранить текущее выделенное значение
  в атоме, инкрементировать его когда задача пропускается далее и вычитать по хуку, который будет добавлен в
  сущность task и передан далее в обработку. Хук должен быть карирован (partial) размером книги в текущей таске,
  чтобы потом не пришлось его вычислять.
- подготовка книги:
  - pdf нужно просто скачать. поскольку файл скорее всего будет лежать в облаке, его необходимо предварительно
    скачать с помощью brctl download и дождаться момента когда он будет скачан. Функции для этого уже
    реализованы в файле [[file:src/ibooks_migration/icloud/core.clj]]:
    - dataless? - проверяет атрибут dataless, если он true - значит локально на диске лежит только заглушка,
      файл фактически не скачан
    - brctl-download
    - brctl-evict
  - epub обычно лежит в распакованном виде, поэтому надо сперва скачать директорию и все вложенные файлы.
    После этого необходимо заново собрать исходный epub-архив во временной директории, не включая файлы,
    которые могли быть добавлены самим iBooks.app после распаковки. На дальнейшие шаги должен передаваться
    именно этот временный архив, а не директория из managed storage
    - при пересборке нельзя полагаться на то, что содержимое всегда лежит в OEBPS. Встречаются как минимум
      варианты с OEBPS, OPS и файлами публикации в корне контейнера. Источник истины для пересборки:
      META-INF/container.xml -> package document (.opf) -> manifest
    - в архив обязательно должны входить container files, необходимые для epub-контейнера
      (mimetype, META-INF/container.xml и другие релевантные файлы контейнера), а также publication resources
      из manifest package document
    - из локальной директории iBooks не нужно переносить iTunesMetadata.plist и iTunesMetadata-original.plist:
      это локальные метаданные Apple/iTunes, а не часть публикации
    - если присутствует META-INF/com.apple.ibooks.display-options.xml, его следует сохранять: это Apple Display
      Options file, то есть Apple-специфичные layout metadata для EPUB 2, а не локальный мусор библиотеки
  - ibooks игнорируем - их обрабатывать не нужно

  В конце этого этапа у нас должен быть файл, с которым мы можем проводить дальнейшие манипуляции.
  Кроме того на этом же этапе необходимо вычислить md5sum, функция для этого уже написана (md5sum) в файле
  [[file:src/ibooks_migration/book.clj]]
- файл необходимо залить на удаленную машину с помощью scp. Корень удаленной директории берется из конфига.
  Файл копируется как есть с перезаписью, дополнительных проверок на то, что он уже существует на удаленной
  стороне, не требуется: признак успешной миграции хранится в локальной базе утилиты
- после заливки необходимо посчитать md5sum на удаленной машине с помощью ssh-md5sum
  (смотри [[file:src/ibooks_migration/book.clj]]) и сравнить локальную и удаленную суммы
- после успешной проверки необходимо выполнить очистку:
  - для файла из iCloud managed storage вызвать brctl-evict и с помощью dataless? дождаться, что он действительно
    уже вытеснен с диска
  - если для epub был собран временный архив, удалить его отдельно, например через rm -f /tmp/%{BOOK}.epub
- как финальный шаг добавить запись в локальную базу о том что данная книга уже обработана - task-done!
  в файле [[file:src/ibooks_migration/db/migrator.clj]]

Разрешенные библиотеки (зависимости):
все разрешенные для использования библиотеки уже добавлены в deps.edn. если целесообразно решить задачу с использованием
какой то дополнительной библиотеки - спроси об этом явно


* TASKS
База ibooks - "/Users/anton/Library/Containers/com.apple.iBooksX/Data/Documents/BKLibrary/BKLibrary-1-091020131601.sqlite"
- [X] Выяснение особенностей хранения epub
  - есть основание полагать что все пути в базе - директории (в выборке из 10 все были директориями)
  - файлы:
    - iTunesMetadata.plist
    - iTunesMetadata-original.plist
    являются Apple-specific и копировать их не нужно
  - валидация можно осуществлять с помощью epubcheck - официального валидатора предоставляемого w3c
  - проверь особенности работы команды brctl download - при вызове команды к ZPATH происходит скачивание всей директории
    включая файлы внутри или нет. Узнать это ты можешь с помощью команды stat -f '%Sf' ${ZPATH} - если есть атрибут
    dataless значит файл не скачан
  - первый драфт алгоритма пересборки такой:
    - создать zip-архив
    - записать mimetype первым и без сжатия
    - добавить все остальные файлы как есть
    - исключить iTunesMetadata.plist
    - исключить iTunesMetadata-original.plist
    - затем прогнать epubcheck ${ARCH_PATH}
- [X] brctl
  - download качает всю директорию, снятие dataless означает что вся директория готова к использованию
  - evict спустя какое то время приводит к вытеснению всех файлов внутри директории
- [X] Напиши код в src/ibooks_migration/epub.clj, который реализует сжатие epub директории в epub zip архив:
  - создать zip-архив
  - записать mimetype первым и без сжатия
  - добавить все остальные файлы как есть
  - исключить iTunesMetadata.plist
  - исключить iTunesMetadata-original.plist
  - результат: реализована функция pack-epub! в [[file:src/ibooks_migration/epub.clj]]
